// Mock product data
export const MOCK_PRODUCTS = [
  {
    id: "dress-001",
    name: "Evelyn Silk Wrap Dress",
    price: 89,
    description: "A flowing silk wrap dress perfect for elegant occasions",
    category: "clothing",
    type: "dress",
    brand: "Lumen",
    color: ["burgundy", "black"],
    size: ["S", "M", "L"],
    style: ["formal", "elegant"],
    material: "silk",
    occasion: ["wedding", "formal"],
    image_url: "https://images.unsplash.com/photo-1704775983143-2c83798831db",
  },
  {
    id: "bag-002",
    name: "Clara Structured Tote",
    price: 120,
    description: "Professional leather tote with multiple compartments",
    category: "accessory",
    type: "handbag",
    brand: "Lumen",
    color: ["tan", "black"],
    size: ["One Size"],
    style: ["professional", "minimalist"],
    material: "leather",
    occasion: ["work", "travel"],
    image_url: "https://images.unsplash.com/photo-1668615561048-7df2e1462ee9",
  },
];
